### ISSUE TITLE
Enhanced Submission Rules - don't scrobble podcasts / ebooks

### ISSUE THREAD

**Issue by konsept** [simple-last-fm-scrobbler/sls#127]
Is it possible to support additional submission criteria such as excluding Podcast plays from scrobbling?

**Comment by HumbleBeeBumbleBee** [comment]
Please continue discussion in #200

**Comment by HumbleBeeBumbleBee** [comment]
I might be able to do this with Dikamilo's #50

**Comment by HumbleBeeBumbleBee** [comment]
After researching, I don't think there is a method for obtaining which pkg is using audio so no way to control scrobbling except for filters.

**Comment by a93h** [comment]
#478 <- see here for the patched code
#479 <- see here for most recent released signed debuggable apk.

**Comment by a93h** [comment]
There is no clear cut criteria for detecting podcasts.
I can however build a user generated words or symbols blacklist for tracks.
[PanoScrobbler Does Some Similar Handling](https://github.com/kawaiiDango/pScrobbler/blob/master/app/src/main/java/com/arn/scrobble/Stuff.kt#L161-L168)
