### ISSUE TITLE
Disable Podkicker and Podkicker pro

### ISSUE THREAD

**Issue by inverse** [simple-last-fm-scrobbler/sls#208]
I've observed that Podkicker Pro at least triggers the default "Android Music Player" intent jazz and thus get's scrobbled. I'll have to investigate this further to see what intents that are actually there.

**Comment by bruzie** [comment]
Literally just noticed this in the last 5 minutes.

**Comment by a93h** [comment]
Should be managed now by the users control of MusicApps options
#479
