### ISSUE TITLE
Love current track requires scrobbling the track

### ISSUE THREAD

**Issue by Row** [simple-last-fm-scrobbler/sls#303]
Love current track does not work, at least not with last.fm.

Steps to reproduce.
1 play a track with dsub
2 press sls notification
3 press love current track at last.fm. notice a message "song ready"
4 open track page on last.fm, the track is not loved.

I have enabled the option scrobble when press scrobble now.

Samsung s6 with android 6.0.1, DSub https://github.com/daneren2005/Subsonic

**Comment by HumbleBeeBumbleBee** [comment]
The current system requires you to listen to/scrobble the song to love the track.
A new database will be added in future so that love track does not require scrobbling.

**Comment by HumbleBeeBumbleBee** [comment]
You may want to try enabling "OnGoing" (and phone notifications)

**Comment by a93h** [comment]
The database has been added.
Thanks very much for the idea.
@Row
