### ISSUE TITLE
Love track notification

### ISSUE THREAD

**Issue by inverse** [simple-last-fm-scrobbler/sls#330]
Perhaps this would be nice to have a configurable persistent notification to love tracks.

**Comment by HumbleBeeBumbleBee** [comment]
A widget maybe?

**Comment by inverse** [comment]
Could be a widget but I never use those ;)

**Comment by HumbleBeeBumbleBee** [comment]
Ok. I'll probably do both.

**Comment by inverse** [comment]
Do you think the feature could be useful?

**Comment by HumbleBeeBumbleBee** [comment]
Certainly.

**Comment by HumbleBeeBumbleBee** [comment]
I'll try to have this done by 1.5.4

**Comment by ALERTua** [comment]
i'd very appreciate a small widget with "love track" button

**Comment by cmpute** [comment]
it'll be awesome to have a love track button!

**Comment by HumbleBeeBumbleBee** [comment]
Ok. I don't have the widget ready yet, but I have added an action button in the notification.

**Comment by whoozwah** [comment]
Would it be possible to have an intent for Tasker to do this as well?

**Comment by HumbleBeeBumbleBee** [comment]
@Nordblum I apologize for the delayed response. I have been extremely busy for the last little while. I am not sure when the next time I will have proper freedom to work on this project again.

For now I can do simple updates.

**Comment by whoozwah** [comment]
Any chance this can get revisited at some point? Having a widget or a tasker intent to love the currently playing track would really be appreciated. Thanks.

**Comment by a93-39a** [comment]
Similar Issue.
https://github.com/tgwizard/sls/issues/303

**Comment by a93h** [comment]
Closing for discussion to continue on #303 
I will add the widget discussion and love track storage feature there.
