### ISSUE TITLE
Set Notification Priority

### ISSUE THREAD

**Issue by michalpulda** [simple-last-fm-scrobbler/sls#346]
Hi,

It would be useful to be able to select notification priority. I have seen many applications with notifications set to lowest and persistent. This should keep the application in memory and running, however the icon is not shown in the status bar (which I personally prefer).

For more see the first answer here http://stackoverflow.com/questions/12758681/android-how-can-i-put-my-notification-on-top-of-notification-area

Also, the notification could have a love button, but maybe I'm asking to much. :-)

Thanks!
Michal

**Comment by HumbleBeeBumbleBee** [comment]
Thank you very much for this.
I will set the default to PRIORITY_MIN.

**Comment by a93h** [comment]
#487
