### ISSUE TITLE
"Android Music Player" Apps not installed

### ISSUE THREAD

**Issue by MisterJenssen** [simple-last-fm-scrobbler/sls#367]
After successfully using sls on my old, almost broken, LG L90 I deceided to buy a new phone. Yesterday I received my new phone, a Samsung Galaxy A3 (Android 6.0.1).
When I installed SLS, every seemed to go ok. I loggid in without any problems and I played some music on the device from Spotify and the Samsung Music app, for Spotify everything goes well (I had to uncheck Spotify because I use the functionality which is build in the app itself). The Samsung Music app does display as "Android Music Player" Apps, but when I check it to scrobble it displays "This app is not installed" and doesn't scrobble, I also don't get Phone Notifications despite it is activated.

Out of curiosity I tried the official Last.fm app, and it seems to scrobble just fine. But I prefer sls, because I can check and correct the scrobble data before sending it to last fm (still working on fixing my mp3's metadata)

As a music lover and a student embedded software engineer, I hoped someone could help and explain to me why it isn't working.

**Comment by betsythefc** [comment]
I am also having this problem.
Samsung Note 4, Vanilla Music Player.
Installed both Vanilla and SLS from F-Droid

**Comment by magnetikonline** [comment]
I also get this identification issue with a Samsung S6 and android 6/7 using Google Music. 

It might be due to the fact this app is provided in the base android install? 

Everything still works - just doesn't identify the app.

**Comment by shishpipi** [comment]
The same issue on my Samsung S8+ when I try to play music in 'Samsung Music' application.
At the same time sceobbling works from foobar2000 but I like standard Samsung's  'Samsung Music' application

**Comment by a93h** [comment]
The app itself package id is not installed,
however several apps use the receiver to share data.
This simply implies that the original android app is not installed.
If you are having bugs or issues I can recommend updating to the newest to signed debuggable apk.
#479
