### ISSUE TITLE
SLS sends Now Playing notifications but doesn't scrobble tracks

### ISSUE THREAD

**Issue by danhash** [simple-last-fm-scrobbler/sls#369]
I have a Samsung Galaxy S7 (SM-G930T) running Android 7.0.

SLS will correctly send Now Playing notifications to Last.fm for Poweramp (I have the Pro version), Google Play Music, and Amazon Music. However, most of the time, only a Now Playing notification is sent and SLS doesn't actually scrobble the track. This happened on the previous version of Android as well (when I was on 6.x, before I upgraded to 7.0).

Since this happens across three separate music player apps, I don't believe the problem to be with Poweramp, Google Play Music, or Amazon Music.

**Comment by marekceglowski** [comment]
Getting the same issue since 6.x. I've been having other issues with apps that run in the background as well so I think its OS specific. Since 6.x you seem to have to allow permissions for everything now after installation so there must be some differences in how things work now.

Its picking up the tracks from the apps just fine but I believe the API calls to Last.fm aren't going through. Not an android developer so I'm not sure how I would go about debugging this myself. I'm on a OnePlus 3 running 7.1.1 (however I noticed SLS hasn't been working for me since 6.x).

**Comment by BalooUriza** [comment]
I'm getting a notification telling me that this version of the app is deprecated, please upgrade. Probably an API issue, libre.fm scrobbles still go through

**Comment by danhash** [comment]
My last successful scrobble to Last.fm was 40 minutes ago (3/31/17 11:20am ET). Just in the last 40 minutes I've started getting the notification "This version of the app is deprecated, please upgrade"

However, I am on the latest version (1.5.3), and there is not a later version available on Github or Google Play.

Scrobbling is now broken.

**Comment by hyalum** [comment]
This is happening to me as well.

**Comment by hyalum** [comment]
„We are currently experiencing difficulties and as such some users may have problems scrobbling to their profile. We apologise for any inconvenience caused by this; our engineers are working on this.

Posted about 15 minutes ago by jon”

**Comment by danhash** [comment]
Looks like the "deprecated" notice is now a known issue per http://status.last.fm/ and the support forums (https://getsatisfaction.com/lastfm/topics/scrobbles-doesnt-work). So that will be a separate issue than this bug.

**Comment by danhash** [comment]
@marekceglowski,
Ignoring the current issue with API calls, I don't believe this bug (with Now Playing being submitted but not scrobbles) is related to failed API calls, because when viewing Status in SLS, the "Last scrobble submitted at" field isn't updated. This means that SLS did not send the scrobble (and that it's not an issue with Last.fm's APIs).

**Comment by marekceglowski** [comment]
I just checked and it scrobbled some stuff from this morning as soon as I opened the app. My settings are "Standard" so it should have been scribbling after every track. :S Not sure why it worked in general just now as it wasn't before, even after opening the SLS app to check the status.

As for why it isn't scrobbling right away, I feel like that must be an issue with my OS blocking certain functionality from background apps (my phone came with OxygenOS). I only think this cause other apps that should notify me sometimes don't. I dunno, I'm not even sure if I'm experiencing the same issue as you guys or if it's something else.

**Comment by danhash** [comment]
@marekceglowski,
That sounds like a different issue than this bug report. This bug report is for SLS sending a Now Playing notification but then not scrobbling the track. If you aren't seeing Now Playing notifications or scrobbles, or if you are seeing delayed scrobbles, that is a different issue. What I am reporting isn't SLS just not scrobbling at all or scrobbling late, it's that SLS is enabled and active and sending Now Playing notifications but not sending scrobbles for those same tracks.

**Comment by toxicwolf** [comment]
I'm having a similar issue, although with just one track in particular. SLS sends a Now Playing notification for the track, but refuses to scrobble it. All other tracks scrobble fine however.

**Comment by danhash** [comment]
How long is the track? If the track is short enough, it won't be scrobbled.

**Comment by jflory7** [comment]
Just to chime in here, there might be a connection with #373. Also, has anyone tried comparing this behavior to when their phone / handset is charging or if it's on battery? This seems to be the problem for me in #373.

**Comment by danhash** [comment]
@jflory7, #373 is totally unrelated; in that bug report, SLS caches the scrobbles.

My bug report is for SLS not even caching the scrobbles: it detects the song playing and sends a Now Playing notification, but it never scrobbles the track.

**Comment by volhovM** [comment]
I have the exact same issue on xperia z5c, android  7.0, using Google music. All permissions (the only one in fact) are given, app is placed in power saving mode exceptions list.

**Comment by danhash** [comment]
Scrobbling with Google Play Music has been working pretty consistently for me, but scrobbling with Poweramp has been very inconsistent (though Now Playing is always sent).

**Comment by danhash** [comment]
As another test, I enabled the "**Ongoing**" and "**Phone Notifications**" options, and it has not made any difference; Poweramp scrobbling still does not work.

**Comment by a93h** [comment]
#479 
Please discuss any new issues after installing the latest signed debuggable apk.
Thanks.
