### ISSUE TITLE
SLS doesn't include Recording MBID

### ISSUE THREAD

**Issue by Freso** [simple-last-fm-scrobbler/sls#381]
I just looked at the SQLite cache of scrobbles waiting to be sent, and I noticed that the `mbid` column was completely empty. I know that all of my music on my phone are tagged with full sets of MusicBrainz IDs, which includes Recording MBIDs, so they should be available.

**Comment by Freso** [comment]
Is this maybe an issue of my player ([Vanilla Music](https://github.com/vanilla-music/vanilla)) not exposing the IDs? Should I file an issue with them to expose IDs?

**Comment by a93h** [comment]
Most players do not expose those IDs,
SLS does have the functionality to receive them though.

**Comment by a93h** [comment]
The functionality has been included.
Android does not expose this inside their stock broadcasts anymore.
The original android will accept this now, however I am closing, deprecated.
#470
