### ISSUE TITLE
Persistent "Simple Last.fm Scrobbler is running in the background" notification in Android O

### ISSUE THREAD

**Issue by Wikiwix** [simple-last-fm-scrobbler/sls#384]
In Android O there is a persistent notification telling that SLS is running in the background.
I am not sure whether there is anything one can do about it, but one should at least look into it.

**Comment by inverse** [comment]
Def should be worked on.

**Comment by HumbleBeeBumbleBee** [comment]
Yes ... I have been trying to please everybody programatically because most people don't understand battery optimization.
Thanks!

**Comment by a93h** [comment]
See #488 
The most recent version #479 pre-release should work.
Download the apk in the link.
