### ISSUE TITLE
MediaMonkey reads artist tag different than Last.FM

### ISSUE THREAD

**Issue by DasBlatt** [simple-last-fm-scrobbler/sls#386]
MediaMonkey seperates several artists with a ';' in the artist tag. Last.FM reads the whole artist tag as one artist. This leads to the problem that it doesn't recognize and scrobble the right song.

A fix for this issue would be if the app would have an option to only submit the first listed artist and cut of the rest after the first ';'

**Comment by HumbleBeeBumbleBee** [comment]
Hi @DasBlatt 
Several individuals have attempted such fixes.

I want to add them however, I just need some rigorous testing first...

https://github.com/tgwizard/sls/pull/50
https://github.com/tgwizard/sls/pull/371

**Comment by a93h** [comment]
The most recent version #479 pre-release should work.
Download the apk in the link.
