### ISSUE TITLE
Scrobbles not recognized from Vanilla Music when file is not in MediaStore.

### ISSUE THREAD

**Issue by dseomn** [simple-last-fm-scrobbler/sls#388]
I'm using Vanilla Music with stock broadcasts (I couldn't get it to work with the Scrobble Droid API, but that's probably an unrelated issue). When I play a file that's in MediaStore, SLS recognizes it correctly, but when I play any other file, nothing happens in SLS. I'm not sure if this is a bug in Vanilla or in SLS, or intended behavior, but it confused me for a long time until I figured out how to add files to MediaStore.

**Comment by HumbleBeeBumbleBee** [comment]
I will try to fix as soon as I can. Thank you!

**Comment by a93h** [comment]
The most recent version #479 pre-release should work.
Download the apk in the link.
