### ISSUE TITLE
poweramp alpha not being scrobbled?

### ISSUE THREAD

**Issue by McNippleson** [simple-last-fm-scrobbler/sls#389]
Updated to PA alpha, in its settings "scrobble with simple last.fm scrobbler" is ticked, in SLS poweramp is ticked. However nothing is being scrobbled.

**Comment by riesza** [comment]
Same issue. It parses 'now playing' but doesn't submit the scrobbles.

**Comment by HumbleBeeBumbleBee** [comment]
Could you please share the link to the application?

**Comment by riesza** [comment]
http://forum.powerampapp.com/topic/8494-poweramp-alpha-build-700/ This should be it

**Comment by HumbleBeeBumbleBee** [comment]
Thanks, alpha builds from poweramp have been known to have scrobbling bugs. They usually get fixed upon release. I will see what I can do as soon as I have time.
Thank you.

**Comment by McNippleson** [comment]
Well unfortunately release of poweramp is unlikely anytime soon. The alpha itself is like a year old?

**Comment by a93h** [comment]
#479 
Should work just fine with the new signed android apk inside the pre-release.
