### ISSUE TITLE
Login Issues

### ISSUE THREAD

**Issue by inverse** [simple-last-fm-scrobbler/sls#425]
Anyone else experiencing login issues? Perhaps we should go down the token based auth root.

**Comment by G00fY2** [comment]
Maybe the same as my observation? #431

**Comment by inverse** [comment]
Could be. However I certainly feel like a token based auth approach would be better. Do you know what I mean?

**Comment by a93h** [comment]
Seems G00fY2's fix works for now.
If I start to notice more network errors from users.
I'll look into changing up Simple Scrobbler's code more.
