### ISSUE TITLE
Simple Last.fm scrobbler stops scrobbling randomly.

### ISSUE THREAD

**Issue by Almostbloop** [simple-last-fm-scrobbler/sls#442]
The app seems to stop scrobbling randomly for periods of time (between 12h-72h so far). Not sure what causes this to happen/stop.

This started happening a week ago after I reinstalled the app. I have uninstalled and reinstalled the app since but that didn't solve the problem.

I use google play music with a Huawei P10 Lite

**Comment by a93h** [comment]
#479 <- please try the newest signed debuggable apk.
Thanks.
