### ISSUE TITLE
CR: Clean up track titles

### ISSUE THREAD

**Issue by r4taw2mg** [simple-last-fm-scrobbler/sls#448]
This is a change request.

Most scrobblers are unnerved by Spotify et al. naming songs 'Blabla [Explicit] (Super deluxe edition) - Remastered 2022)'. As these titles get scrobbled, some of the titles listened to, get more than one entry in your list of scrobbles. last.fm is not really tackling the problem, but SLS could do it to a certain extend.

Please add an option to remove those Explicit|Remastered|Edition strings from the titles before sending them to the scrobble DB.

If you need a proposal, what strings to eleminate as regex, please contact me.

**Comment by a93h** [comment]
Hello friend.
This bug fits with the issues in #489 , also I can add a tool to block the brackets and also their contents uniquely.
This is being discussed in #489, please continue there.
