### ISSUE TITLE
sls scrobbles from Spotify when the Spotify option is disabled

### ISSUE THREAD

**Issue by eignatenkov** [simple-last-fm-scrobbler/sls#449]
Huawei P10, Android 8.0.0.
I have Spotify option disabled in sls, because Spotify scrobbles for itself. But if the "Android Music Player" Apps option is enabled (which I use to get scrobbles from foobar player) it still scrobbles from Spotify, so that I have duplicated Spotify scrobbles, coming both from sls and Spotify.

**Comment by a93-39a** [comment]
Did you log into last.fm via Spotify?

**Comment by a93h** [comment]
Closed as not possible with SLS v1.4.7
