### ISSUE TITLE
scrobbles last listened to item on soundcloud perpetually

### ISSUE THREAD

**Issue by Benji222** [simple-last-fm-scrobbler/sls#465]
not sure why but whatever my last played thing in soundcloud is it endlessly scrobbles that over and over. this seemingly when i start a listening session later

**Comment by a93-39a** [comment]
This is a common problem that I am working on.

**Comment by Benji222** [comment]
appreciate the reply and glad to hear ity'all rock. On Aug 8, 2019 1:22 PM, Austin H <notifications@github.com> wrote:This is a common problem that I am working on.

**Comment by a93-39a** [comment]
My best bet is only storing tracks when a good duration of the time the app is actively using the sound focus bit in android.
Luckily android requires apps tell android when they are using audio output.
This [link](https://developer.android.com/guide/topics/media-apps/audio-focus) really describes what I need to look at implementing.

**Comment by a93h** [comment]
#479 <- please try the newest signed debuggable android apk.
