### ISSUE TITLE
v1.5.8 vCode 49 Pre-release

### ISSUE THREAD

**Issue by a93h** [simple-last-fm-scrobbler/sls#479]
[Pre-Release v3 SLS 1.5.8 vCode 49 pre-v12](https://github.com/simple-last-fm-scrobbler/sls/releases/tag/v1.5.8-pre-v12)

As described in the link, the app has gone through some changes.
I need as many people as possible to help debug them for now.

Thanks,
Austin H.

**Comment by drjobec** [comment]
On FireTV (v1), starting the app just flashes a white screen briefly and then it exits.

**Comment by a93h** [comment]
This is a somewhat unusual device for me.
Do you have any debug logs?

**Comment by a93h** [comment]
The main issue with non-standard android products is library dependencies and certain other things.
Did it work before?

**Comment by drjobec** [comment]
I understand the problem of this non-standard device. If the app would work, that would be nice, but if that's too much work, also that is fully understandable.

Working before: Yes. And no. The app loaded, the settings could be adjusted, and relatively long it even scrobbled properly. Until after some OS update (I don't know anymore at which point) the scrobbling stopped. Still, the app didn't crash as the current pre-release does.

I'm not an SW-developer, but more on the algorithmic side. Still, if I can somehow help, I'm happy to do so. Do you have an idea where to look for the logs?

**Comment by a93h** [comment]
1. [Amazon FireTV Debug](https://developer.amazon.com/docs/fire-tv/connecting-adb-to-device.html)
2. [SLS Debugging](https://github.com/simple-last-fm-scrobbler/sls/wiki/Debugging-Crashes)

**Comment by a93h** [comment]
Could you share your Android Operating system version please too?

**Comment by drjobec** [comment]
Log starting from opening the app and ending after the crash: [https://hastebin.com/zocidifaga.makefile](https://hastebin.com/zocidifaga.makefile).

The logcat command from your instructions didn't work as expected, but dumped also various other information. This is probably related to this: [https://forums.developer.amazon.com/questions/55585/firetv-crash-call-stack-are-not-available-in-adb-l.html](https://forums.developer.amazon.com/questions/55585/firetv-crash-call-stack-are-not-available-in-adb-l.html)

The OS is "Fire OS 5.2.7.1", which was branched from Android 5, to my understanding.

**Comment by nswint** [comment]
Pre8 is reporting the last added music player after the colon instead of the active player.
The active player is pocketcasts.  The player being reported in the notification is Amazon music. 
(url)[https://photos.app.goo.gl/HqaqjWQeBBb54Zcu6](url)

**Comment by a93h** [comment]
Thanks nswint and drobec,
I am currently looking into resolving both your considerations.
Thanks,
Austin H

**Comment by a93h** [comment]
@drjobec any chance you could try this .apk ?
[sls-v1.5.8-vCode-49_v8.apk-debug.testing.zip](https://github.com/simple-last-fm-scrobbler/sls/files/3561333/sls-v1.5.8-vCode-49_v8.apk-debug.testing.zip)

**Comment by drjobec** [comment]
Looking slightly better. 
The permission page opens, but the green/red buttons to control toggle the setting are on the right border of the screen and practically impossible to control (can't see where the selection currently is and even with some liberal button smashing I was able to toggle just one of them). Also, assuming that I managed to hit the "Continue", it didn't close the page. Smashing the back-button on the remote showed that the normal setting page is behind the permissions, but that's now blocking everything.

**Comment by a93h** [comment]
Did some read text appear for you on the bottom of the permissions pages?

**Comment by a93h** [comment]
@drjobec 
https://github.com/simple-last-fm-scrobbler/sls/releases
Please install version 10 of the pre-release.
It will contain instruction on how to fix the problems.

**Comment by drjobec** [comment]
On the permissions screen, "Notification Listener" is gray, while others are green. With some blind clicking (using a remote doesn't show where the cursor is at) displayed the red hint text about notifications ignore list. Checking the device settings still shows all notifications from SLS being allowed.

**Comment by a93h** [comment]
Sorry it's called "notification access".

**Comment by drjobec** [comment]
Maybe I just didn't find it, but I found no way of controlling the app permissions in this version of FireOS. It can be because it's still based on so old Android API (v22). Instead, all permissions should be presented in the manifest in apk, and I didn't find BIND_NOTIFICATION_LISTENER_SERVICE listed there. 

Could this be the issue?

**Comment by a93h** [comment]
Yes, this is exactly the issue unfortunately.
I am researching now.

**Comment by a93h** [comment]
I am sure you were thorough but did you look here ?

Settings > Sounds & Notifications > Manage notification listeners

**Comment by drjobec** [comment]
That doesn't exist on this gen1 device. There are:
- Settings > Notifications (displays current notifications)
- Settings > Display & Sound (audio and video settings)
- Settings > Applications > Manage Installed Applications (launch, force stop, uninstall, clear data, clear cache)
- Settings > Preferences > Notification Settings (turn on/off Do not disturb, turn on/off notifications from individual apps)

**Comment by a93h** [comment]
It looks like they have removed this possibility of notification reading from their Operating System.

**Comment by a93h** [comment]
This means, like I said previously, device specific code and reading the old way for broadcasts.

**Comment by a93h** [comment]
I can add a disable notification listener button to the options list if you want?
The downside is that it will miss the new functionality offered.
Unfortunately the new functionality is required to try new music apps and hence Notification Listener.

**Comment by a93h** [comment]
@nswint I have your fix in a minute.  pre-v11

**Comment by a93h** [comment]
@nswint It's at the top there.

**Comment by nswint** [comment]
> @nswint It's at the top there.

Thanks. pre-v11 is super broken now

- I wasn't prompted for the new/updated listener permissions.  I reinstalled and saw the requests for the new permissions. (Reinstall gave me a host of new issues with session keys and authentication.)
- After all 4 permissions are allowed the app automatically continues without out pressing the continue button
- Last.fm give wrongs username/password/token errors.  I've cleared the username and session key.
  I'm using the right username/password
- Pocketcasts show empty now playing information.
- Pocketcasts no longer scrobbles
- Google Play music only scrobbles once and doesn't scrobble any more
- Settings seem to persist now.  Are these saved locally in a folder or in google cloud now? 

No scrobble information
[https://photos.app.goo.gl/pysXrsRDjHPk4UmB9](url)

Scrobble from 1.5 songs prior. The song reported 2 minutes prior that it scrobbled but I finished the song 6 minutes prior.  I have the setting to submit at 50% of the song so it should have scrobbed about 8 minutes prior.

[https://photos.app.goo.gl/zJZvurQebzgukJJT9](url)

**Comment by a93h** [comment]
- I wasn't prompted for the new/updated listener permissions.  I reinstalled and saw the requests for the new permissions. (Reinstall gave me a host of new issues with session keys and authentication.)
**reinstall sometimes affects shared preference keys (aka I cannot change that)**
- After all 4 permissions are allowed the app automatically continues without out pressing the continue button **is expected behavior**

- Last.fm give wrongs username/password/token errors.  I've cleared the username and session key.
  I'm using the right username/password
** Can you share a bit more information? If you're a developer a debug log dump could help me out.**
- Pocketcasts show empty now playing information. **this will happen if you are not logged in**
- Pocketcasts no longer scrobbles **this will happen if you are not logged in**
- Google Play music only scrobbles once and doesn't scrobble any more  **something is wrong**
- Settings seem to persist now.  Are these saved locally in a folder or in google cloud now?  **locally**

**Comment by nswint** [comment]
> * I wasn't prompted for the new/updated listener permissions.  I reinstalled and saw the requests for the new permissions. (Reinstall gave me a host of new issues with session keys and authentication.)
>   **reinstall sometimes affects shared preference keys (aka I cannot change that)**
>   **if you set listener permissions once, you should be ok**
> * After all 4 permissions are allowed the app automatically continues without out pressing the continue button **is expected behavior**
> * Last.fm give wrongs username/password/token errors.  I've cleared the username and session key.
>   I'm using the right username/password
>   **Can you share a bit more information? If you're a developer a debug log dump could help me out.**
> * Pocketcasts show empty now playing information. **this will happen if you are not logged in**
> * Pocketcasts no longer scrobbles **this will happen if you are not logged in**
> * Google Play music only scrobbles once and doesn't scrobble any more  **something is wrong**
> * Settings seem to persist now.  Are these saved locally in a folder or in google cloud now?  **locally**

What is an email address that I can mail you the link to the debug log?  Debug logs sometimes might contain some passwords and such and the number of bots that comb github for passwords and other credentials probably outnumber living humans.

**Comment by a93h** [comment]
simple.last.fm.scrobbler@gmail.com

**Comment by a93h** [comment]
Ok I worked last night and this morning.
It seems that the notification controller is much more dense than I thought.
I was not issuing access to the media session correctly nor was I registering the callbacks correctly.
After the first callback the whole system fails to recognize the music players.
Apologies for the delay and issues therein.

**Comment by a93h** [comment]
https://github.com/simple-last-fm-scrobbler/sls/releases/tag/v1.5.8-pre-v12

**Comment by a93h** [comment]
I might as well restart the one week rule for pre-release.
That will mean waiting until September 9th or 10th until I release the final apk.

**Comment by a93h** [comment]
@nswint  Apologies if this question seems crass, yet I wonder if the new release is working well for you?

**Comment by a93h** [comment]
@drjobec  I think I need to add a special apk for your device or add a bypass option to the permissions system for legacy operating systems or special operating systems. I will create a new issue.

**Comment by drjobec** [comment]
I leave it to your consideration if the extra effort is worth it. Personally, I would appreciate it, but such "old" systems are probably getting already quite rare. The reason I'm still using the Gen1 device is that it's still working, and to date it's the only FireTV with a separate digital audio-out allowing listening to music without the TV being on (without an AVR). 
It would be the easiest, if the required permission could be granted somehow automatically during installation, but I know too little of Android apps and permissions to know if this is even possible.
Thanks anyway for your effort!

**Comment by a93h** [comment]
No it's okay. I'll make it happen.
Just give me some time.
Like I said. You can bypass the functionality, but you will need to rely on old broadcasts.
Android before Oreo will work.

**Comment by nswint** [comment]
So far so good.  No issues running on  Android 10.

**Comment by a93h** [comment]
#508 @drjobec
