### ISSUE TITLE
1.4.8 pre 11 not picking up any notifications

### ISSUE THREAD

**Issue by djryan** [simple-last-fm-scrobbler/sls#495]
Upgraded to 1.4.8 pre 11 and nothing is scrobbling.

![Screenshot_20190902-173524](https://user-images.githubusercontent.com/1846148/64127048-1b6f7580-cda8-11e9-9f03-76d47d793f1e.png)

Despite reinstalling and making sure all permissions are set. 

And I'm currently logged in.

**Comment by djryan** [comment]
Update.  Did a little more digging and it looks like it’s just Podcast Addict that’s failing.  I loaded up Spotify and that picks up new intents.

Next test will be to uninstall and reinstall and see if it’s the currently in favour app that doesn’t get detected as new.

**Comment by djryan** [comment]
No, it detects Podcast Addict by default.  If I clear all apps and try and force it to detect again, it doesn’t.

**Comment by a93h** [comment]
Strange.

**Comment by a93h** [comment]
Ok I worked last night and this morning.
It seems that the notification controller is much more dense than I thought.
I was not issuing access to the media session correctly nor was I registering the callbacks correctly.
After the first callback the whole system fails to recognize the music players.

**Comment by a93h** [comment]
https://github.com/simple-last-fm-scrobbler/sls/releases/tag/v1.5.8-pre-v12

**Comment by a93h** [comment]
@djryan  Apologies if this question seems crass, yet I wonder if the new release is working well for you?

**Comment by a93h** [comment]
I believe I have resolved this in version pre-12

**Comment by djryan** [comment]
Works a treat now!  Thanks.

**Comment by a93h** [comment]
Super!!!
I tried the new system upgrade.
It works, however I noticed the media session manager might take a minute to pick up new music players.
Thanks for the time and the new idea with regex style code.
