### ISSUE TITLE
1,6,1 notification stays up even when force close

### ISSUE THREAD

**Issue by whinette** [simple-last-fm-scrobbler/sls#506]
Updated to the latest version from playstore (had the old icon before that, do not know the exact version).

Simple Scrobbler notification is alway up, even after a force close of the application.
Suggestion : display notification only when something is scrobbled @ easy access to like / have a option to enable or disable notification (I don't want a notification that is always displayed and would prefer the old system to launch the app by myself).

**Comment by a93h** [comment]
Please try disabling "Active App Notification" in "Options" Menu

**Comment by whinette** [comment]
Indeed, it was greyed out @ default options and did not thought of this.

**Comment by a93h** [comment]
Thanks for making an issue on GitHub fellow Scrobbler.

Is everything working as you hoped now?

**Comment by whinette** [comment]
Scrobbling doesn't seems to work (bubbleupnp, activated in the applications) without the notification.
Statut doesn't display in the last.fm section the number of scrobling (the update wiped out all the stats inside the app btw).

I will rollback for the time being. :)

**Comment by a93h** [comment]
What music app are you using?

**Comment by whinette** [comment]
https://play.google.com/store/apps/details?id=com.bubblesoft.android.bubbleupnp.unlocker

**Comment by a93h** [comment]
Ok I am testing right now.

**Comment by a93h** [comment]
I managed to get it to work,
It required me switching between different music apps.

#503

**Comment by a93h** [comment]
#508
