### ISSUE TITLE
Versions 1.5.8 to 1.6.1 don't work with GoneMad Music Player

### ISSUE THREAD

**Issue by WolfFhang** [simple-last-fm-scrobbler/sls#507]
I'll preface this with saying I reverted back to 1.5.7 for the time being so that I can still use the app as intended. But these issues persisted from the Play Store updates of 1.6.0 and 1.6.1, as well as the github APK for 1.5.8.

### **General Info**
I'm using GoneMad Music Player
(Current Play Store version + Unlocker, not v3.0 beta:
https://play.google.com/store/apps/details?id=gonemad.gmmp
https://play.google.com/store/apps/details?id=gonemad.gmmp.unlocker)

The only settings I change/disable in SLS are Active App Notification and the Roaming related ones
I'm on a Moto G7 with Android 9 (Pie)

### **Issues**
Version 1.5.8 of the app still at least picks up/recognizes GoneMad Music Player but won't push Now Playing or scrobble (I didn't try with the Active App Notification option on) , but 1.60 / 1.6.1 don't even pick up GMMP if I remove it from "Enabled Apps" and try to re-add it. Though when I did try before removing GMMP,  no matter what options were used I couldn't get the app to push Now Playing or even a full scrobble.

I guess it should also be noted that in GMMP under Settings -> General -> Scrobbler Preferences, there is a checkbox to "Enable scrobbling with simple lastfm scrobbler". I don't know if this means they also need to fix some things on their end because of the SLS rebrand or not to restore functionality

Also on an unrelated and strange note, since the update (I think 1.6.0, not sure about 1.5.8) in the Enabled Apps section SLS has also picked up "Notification Controller" as an app. Not sure if this is normal or is helpful to know.

**Comment by a93h** [comment]
Hello fellow Scrobbler,
I am building a fix right this moment.

**Comment by a93h** [comment]
Please move discussion here.
#503

**Comment by a93h** [comment]
#508
