### ISSUE TITLE
 After updating to 1.6.2, App crashes on "Scrobble Now"

### ISSUE THREAD

**Issue by Chaparro** [simple-last-fm-scrobbler/sls#510]
SLS Version : (1.6.2)
    Issue: App crashes on scrobble now after updating to 1.6.2, cache i'm attempting to scrobble is from the last 3 weeks.

   Parameters:

-         What:  App Crashing attempting Scrobble Now to last.fm
-         Where: Scrobble Cache 
-         When: "I clicked Scrobble Now", or by attempting to view scrobble cache and clicking on any song.
-         How:  Manual Button Click, dialog appears 'Simple Scrobbler keeps stopping'

    **Android Version** (preferred): (9)
    **Music App(s)** :  Pulsar Music Player
    **Detected Music Apps(s)**: Pulsar, Android Music Player (not installed)
    **Phone Model** : Xiaomi Mi A1

Had to authenticate with Last FM again after updating, but it seems to authenticate correctly.
Can provide screenshots if desired.

Note: **Correction Rules** also crashes the app

**Comment by a93h** [comment]
Are all the permissions activated for you device or did you bypass?

**Comment by a93h** [comment]
I have been trying to recreate your bug without success.
Do you mind exporting the database?
simple.last.fm.scrobbler@gmail.com

I can check if any of the tracks have unusual data.

Also, what is the track correction please?

**Comment by dropdan** [comment]
Just updated via Pay Store and I'm facing the same issue. Had to authenticate to last.fm again and everytime I click on "Scrobble Now" the app crashes.
It also crashes when I press "Correction Rules".

Android Version: 8.0
Music Player: Poweramp/Sony Stock Music Player
Phone Model: Xperia XZ

**Comment by a93h** [comment]
Hello friends,
If one of you could share the fellowing data.
It should only have Simple Scrobbler data if you follow the instructions.

https://github.com/simple-last-fm-scrobbler/sls/wiki/Debugging-Crashes

**Comment by a93h** [comment]
Unfortunately I cannot recreate this bug.

**Comment by a93h** [comment]
Friends are you logged in?

**Comment by a93h** [comment]
I have found the problem.
It is rather serious and somewhat my fault for not foreseeing this problem.
