### ISSUE TITLE
ListenBrainz login no longer working

### ISSUE THREAD

**Issue by jhoff80** [simple-last-fm-scrobbler/sls#515]
Not sure what version this started in but ListenBrainz (the non-server version) no longer logs in.  Seems to be new since the rebrand but I'm not sure.

**Comment by IvanDSM** [comment]
Can confirm, happening since yesterday's Google Play Store update. Trying to log into ListenBrainz causes the app to crash.

**Comment by goodevilgenius** [comment]
With v1.6.3, either installed through Play Store, or sideloaded from Releases page, it wouldn't work for me, either. It would just crash when I put in the info.

Downgrading to v1.6.2 (from Releases page) fixed the issue for me, so this is specifically a regression on 1.6.2

An additional, possibly related issue, is that upon upgrading to v1.6.3, my login details were mixed up. My ListenBrainz user name was listed under last.fm, my last.fm under libre.fm, and my libre.fm listed under ListenBrainz. Clearing them out and reentering worked fine.

**Comment by goodevilgenius** [comment]
I'm guessing these changes are the cause: https://github.com/simple-last-fm-scrobbler/sls/compare/v1.6.2...v1.6.3#diff-6832bb0fda02fa478eee5e38d292e57e

**Comment by a93h** [comment]
Ok. I'm off to work.
Sorry about that ListenBrainz fans.

**Comment by jhoff80** [comment]
Seems to be fixed, thanks.
