### ISSUE TITLE
Can't remove blank notifcation

### ISSUE THREAD

**Issue by pwd-github** [simple-last-fm-scrobbler/sls#520]
Version: 1.6.4.
The latest from the Play Store beta.

There's a blank notification with the options to Love and Copy a track, but it can't be removed.

**Comment by a93h** [comment]
"Active App Notification" in "Options" removes the notification.

**Comment by jjok** [comment]
So is it correct that there's permenently a blank notification there?
 
> "Active App Notification" in "Options" removes the notification.

It says it might skip scrobbles if I do that.
