### ISSUE TITLE
Poor Documentation on Android 8.0+ for severity of Notification Listener

### ISSUE THREAD

**Issue by eggsgent** [simple-last-fm-scrobbler/sls#525]
No enabled apps after update to the "new looks" version. Currently having v.1.6.5 installed.

Cleared data, reinstalled and logged in to last.fm, but no enabled apps are updated.

Music apps used:
https://play.google.com/store/apps/details?id=com.foobar2000.foobar2000
https://play.google.com/store/apps/details?id=ch.blinkenlights.android.vanilla

**Comment by a93h** [comment]
Please answer these two questions.
What version of Android? (Should be greater than Android version 5.0 AKA Lollipop for Foobar2000)
If you Android is greater than Lollipop What permissions do you have enabled?

**Comment by eggsgent** [comment]
Hi, Android 9.0, all permissions enabled except for access to read notifications.

**Comment by a93h** [comment]
Notification Reading is necessary to detect music,
Was there a popup notification telling Scrobbling would not work?

**Comment by eggsgent** [comment]
This notifications permission isnt needed in the earlier iterations of this app.
This permission is very privacy invasive and easily misused, so I would never consciously want to enable it for this type of app.

**Comment by a93h** [comment]
![Sidesync_capture_September 14, 2019 at 1:20:11 PM EDT](https://user-images.githubusercontent.com/8563086/64911627-6a939f80-d6f2-11e9-949c-59f2971f527d.png)

**Comment by a93h** [comment]
I can garuntee we do no invade or misuse this permission.

**Comment by eggsgent** [comment]
I saw that pop-up, but didnt understand the message in it.

**Comment by eggsgent** [comment]
Which benefit does this version of this app over the older version without this permission?

**Comment by a93h** [comment]
1. This app prides itself on Open Source activity and Transparency with our users.
2. We never collect data.
3. Only music metadata is shared.
A. The benefit this app has, is that it is now compatible with Android Oreo and up.
B. We would have not been able to update the app any longer if we did not change the way we read music metadata.
C. The benefit is that we data music apps through Google's Media Session Library.

Please be aware your private information is safe.

**Comment by a93h** [comment]
[ControllerReceiverService.java](https://github.com/simple-last-fm-scrobbler/sls/blob/master/app/src/main/java/com/adam/aslfms/service/ControllerReceiverService.java)
 * Connects the app to the Media Session Manager
 * Listens only for music data changes
[ControllerReceiverSession.java](https://github.com/simple-last-fm-scrobbler/sls/blob/master/app/src/main/java/com/adam/aslfms/service/ControllerReceiverSession.java)
 * contains static functions for media session management
 * contains simple functions
[ControllerReceiverCallback.java](https://github.com/simple-last-fm-scrobbler/sls/blob/master/app/src/main/java/com/adam/aslfms/service/ControllerReceiverCallback.java)
 * Manages the incoming data form your music apps
 * Manages play-state and metadata changes.

**Comment by a93h** [comment]
https://github.com/simple-last-fm-scrobbler/sls/wiki/Privacy-Concerns

**Comment by eggsgent** [comment]
Thanks, perhaps this issue is then that it is not clear that the reading notification permissions is absolutely needed in order for the app to function. If the user does not accept, the app should quit, and not continue to the settings page with option to login etc.

Version 1.5.7 still works with Android 9 though (at least on all devices ive tried), without the reading notifications permission: https://f-droid.org/en/packages/com.adam.aslfms/

**Comment by a93h** [comment]
I apologize. Yes, due to the way Google has setup the new music metadata sharing system Notification Access is required for Android 8.0 | Oreo | 26.

**Comment by a93h** [comment]
Version 1.5.7 is the old version and yes it will work because Google made a requirement for all developers to upgrade their target minimum Android versions on the Google Play Store.
However F-Droid still has older packages.

**Comment by eggsgent** [comment]
Thanks for the help and explanations. 

Would you consider making the permissions requirement screen improvement so that users must enable all needed permissions before going further?

**Comment by a93h** [comment]
@eggsgent 
I will see what I can do.
Some users have different requirements.
There are special Android devices I am trying to allow them to bypass these settings.
Maybe I will make this value mandatory for versions above android 8.0
Many users were complaining about the new permissions however.
I will consider a legacy version for F-Droid.

**Comment by eggsgent** [comment]
Thanks again for great feedback and support. If the warning message can be made more clear, that's an easy fix, suggestion on wording in previous comment.
