### ISSUE TITLE
App keeps crashing

### ISSUE THREAD

**Issue by felixkonrad** [simple-last-fm-scrobbler/sls#529]
Version used: 1.6.6

What happens: Crash happens.

Steps to reproduce: 
1. Open App.
2. Interact with ans UI Element.
3. App Freezes and crashes.

Android Version: 8.0.0

This was written on mobile because i am travelling. Please excuse formatting and missing information.

**Comment by a93h** [comment]
I found it.

**Comment by insanity35** [comment]
Same issue.

**Comment by a93h** [comment]
Do you both have "Active App Notification" disabled?
This is the cause of the bug.
I fixed it.
I am waiting for Google Play Store to update right now with version 1.6.7

**Comment by insanity35** [comment]
Yes because I don't like the notifications in the tray. Once you turn both off app stops scobbling and crashes constantly. But awesome I'll update as soon as play store lets us.

**Comment by felixkonrad** [comment]
Yes i had that disabled.

Thank sou!

**Comment by insanity35** [comment]
All seems to working well on 1.6.7.

**Comment by felixkonrad** [comment]
Can I close this? it seems to be fixed with 1.6.7 for me

**Comment by a93h** [comment]
Yes, glad it works.
