### ISSUE TITLE
Scrobbles from Qobuz are transmitted, but never show up on last.fm

### ISSUE THREAD

**Issue by FLiNT-13-7** [simple-last-fm-scrobbler/sls#530]
SLS Version: 1.6.6

Issue:
When playing music in Qobuz, the songs are detected, appear in the scrobble cache (if scrobbling is set to manual mode), can be edited and - according to Simple Scrobbler's status report - are submitted to last.fm, but they never actually show up there. Scrobbles from other apps work fine.

Android Version: 9
Music Apps: Qobuz (affected), Deezer, Neutron Music Player
Detected Music Apps: Qobuz, Deezer, Neutron Music Player, Notification Default
Enabled Settings: Standard settings ("When to scrobble" set to manual later on for troubleshooting reasons)
Phone Model: Huawei Honor 9

**Comment by a93h** [comment]
Hello @FLiNT-13-7  has this been resolved?

https://twitter.com/lastfmstatus

I hope you can understand Last.fm has been having problems lately.

**Comment by FLiNT-13-7** [comment]
No, still the same.

I know about last.fm's recent issues (actually mentioned it in#526), but this seems to be unrelated.

"Now playing" works fine, scrobbles from other apps work fine, only scrobbles of tracks played in Qobuz are affected.

Not sure if some sort of app ID is submitted when scrobbling to last.fm, but if so, an option to spoof it might be helpful?!

**Comment by a93h** [comment]
Hello friend,

I just tested and cannot recreate your problem.
The app says it scrobbled.
Are you using the full Quboz version?
Last.fm does not accept tracks played for less than 30 seconds.
Hence we do not scrobble tracks shorter than 30 seconds to Last.fm

If I cannot recreate the problem, I cannot fix the problem.

**Comment by FLiNT-13-7** [comment]
Paid subsription, latest version of both Qobuz (5.1.10) and SLS (1.6.7) apps.

Like I said: Tracks do appear in cache and seem to scrobble fine (i.e. they are listed as "latest scrobble"), but they never actually do show up in my last.fm library. Do yours?

**Comment by FLiNT-13-7** [comment]
Update: Identical behaviour under Android 5.1.1.

**Comment by a93h** [comment]
My scrobbles do show up.

**Comment by FLiNT-13-7** [comment]
![Screenshot_20190917_231743_com qobuz music](https://user-images.githubusercontent.com/36166008/65082233-b9b52b00-d9a5-11e9-8cfb-f1dec9501fb2.png)
![Screenshot_20190917_232436_com adam aslfms](https://user-images.githubusercontent.com/36166008/65082258-c33e9300-d9a5-11e9-960a-225fa4d368c5.png)
![Screenshot_20190917_232558_com adam aslfms](https://user-images.githubusercontent.com/36166008/65082266-c9cd0a80-d9a5-11e9-9177-05bdd06aa136.png)
![Screenshot_20190917_234717_org mozilla firefox](https://user-images.githubusercontent.com/36166008/65082275-cfc2eb80-d9a5-11e9-827c-d5836ba16f8e.png)

**Comment by a93h** [comment]
I'm logged in via VPN to France to use Quboz.
All my Scrobbles work.
I am really finding it impossible to understand why it won't work.

**Comment by FLiNT-13-7** [comment]
I'll see what I can do about the log.

Might take some time, though.

**Comment by FLiNT-13-7** [comment]
Not sure how helpful this information is, but the very same tracks do show up when scrobbled via Pano Scrobbler.

**Comment by a93h** [comment]
I just played "Fly Me To The Dark Side Of The Moon" by "Pink Sinatra" on Quboz and it scrobbled just fine.
I don't know what possibly could be wrong with Simple Scrobbler.

Maybe you can switch to Pano Scrobbler. It has some advantages.
Not sure why you'd want Simpe Scrobbler when you can use Pano Scrobbler instead.

We just adopted the new library functionality, Pano has had it for a long time.

**Comment by a93h** [comment]
I just played Sex Joji by Metronomy and it scrobbled really good.

**Comment by FLiNT-13-7** [comment]
Yeah, I'm going on vacation starting this weekend, so I'll stick with Pano for now. Tbh, I didn't even know it existed until a few days ago.

Still intrigued to find out what causes those scrobbles to vanish, so I'll send you that log once I'm back home.

**Comment by a93h** [comment]
Well since you feel your issue has been resolved, I'll be closing this for now unless somebody reports the same problem.
If you still want to share a log information, then please do even after I close this issue.
I will try and read it to see what's going occurring.

Thanks,
Austin H.
