### ISSUE TITLE
Explain in wiki why notification permissions are now needed

### ISSUE THREAD

**Issue by NickSto** [simple-last-fm-scrobbler/sls#533]
Hey, I appreciate all the work on the app. It's been really great to be able to have my PlayerPro listening logged to Last.fm.

I recently saw that it needs notification permissions, and in trying to understand, I came here (I think I found this through the changelog in the app). I followed the [Privacy Explained](https://github.com/simple-last-fm-scrobbler/sls/wiki/Privacy-Concerns) link at the top of the README, and I'm glad for the explanation.

The wiki page made me feel better, but it didn't answer my main question, which was "Well it worked before, without the permission. Why does it need it now?" I think this is likely the most common thought of users.

I searched around and found issue #525, and now I have an idea what happened, after reading @a93h's comments (starting [here](https://github.com/simple-last-fm-scrobbler/sls/issues/525#issuecomment-531499911)). So I thought I'd suggest explaining that on the wiki page. And maybe a link to info about the Android API change?

Sorry for all the fuss, but unfortunately it's a whopper of a permission to give an app. For instance, any app with that permission could get around the SMS 2-factor authentication most banks use. This being an free & open source app, it's one of the few I'd consider granting it to, but I want to understand what's happening.

**Comment by a93h** [comment]
https://github.com/simple-last-fm-scrobbler/sls/wiki/Privacy-Concerns

**Comment by NickSto** [comment]
@a93h Awesome, that's like exactly what I was looking for. I think I get it now. It sounded like a situation where Google was forcing people onto a new API level, and I guess that was it!

Thanks! I think this "Why?" section will help people in general understand.

**Comment by eggsgent** [comment]
URL is 404
https://github.com/simple-last-fm-scrobbler/sls/wiki/Privacy-Concerns
