### ISSUE TITLE
Can't return back from "Permissions" window

### ISSUE THREAD

**Issue by alexesprit** [simple-last-fm-scrobbler/sls#534]
**Description**
If I press the "Back" button while the "Permissions" window is displayed, I won't be able exit from app using the "Back" button.

**Steps to reproduce the issue**
1. Open Simple Scrobbler.
2. Select the "Options" item. The "Options" window will be opened.
3. Select the "Permissions" item. The "Permissions" window will be opened.
4. Click the "Back" button.  The "Options" window will be opened.
5. Click the "Back" button again.
These steps are screencasted. See screencast 1 below.

**Expected behavior**
The main window is displayed.

**Actual behavior**
The "Permissions" windows is displayed again. If I press the "Back" button, the app will display the "Permissions" window over and over. I won't be able to "exit" from app (AFAIK it's technically not "exit", i.e. the app is still running, but anyway).

**Additional info**
[Screencast 1][screencast1].
[Screencast 2][screencast2] (screencasting first launch).

Also I experience the similar issue with the same window which is displayed on first run. The difference I click on the "Continue" button, then I click on the "Back" button while I'm in main menu. I screencasted this issue too (see screencast 2 above). Let me know if it's not the similar one, and if I need to submit another issue with detailed description.

**Environment**
Version: 1.6.7
OS: MIUI 10.2.3.0 (Android 8.1.0)
Device: Xiaomi Redmi 5 Plus

[screencast1]: https://drive.google.com/file/d/12Dr0Vt4-41TRjKQM7s0wsadTSOCvybJW/view?usp=sharing
[screencast2]: https://drive.google.com/file/d/12O5T66SzdWKCRBIkXWmofcUzEQLuYWup/view?usp=sharing

**Comment by a93h** [comment]
version 1.6.8 should fix this problem once it is Updated to the play store.

**Comment by a93h** [comment]
#535
