### ISSUE TITLE
Enable/Disable app crash

### ISSUE THREAD

**Issue by insanity35** [simple-last-fm-scrobbler/sls#542]
Updated to 1.6.9 and when I go into Enabled apps it crashes instantly.

**Comment by a93h** [comment]
hello @insanity35 is this still a problem?

**Comment by insanity35** [comment]
It started with the 1.6.9 update this morning. If you hit Enabled/Disabled
apps it crashes. I wanted to turn off TuneinRadio scrobbling and crashes
everytime.

**Comment by djryan** [comment]
I’m seeing this on the new version too.

**Comment by insanity35** [comment]
Seems to be fixed in 1.7.0
