### ISSUE TITLE
Podcast name (artist name) includes Date

### ISSUE THREAD

**Issue by Whateverthing** [simple-last-fm-scrobbler/sls#552]
Hi -- First I want to say THANK YOU for your work, especially with all the recent system changes.

I'm happy to see that my podcast app activity (from Podcast Addict) recently started scrobbling again. I recently played the new episode from This American Life. It gets the podcast episode title just fine (like "684: Burn It Down"). But when it picks up the artist name, it includes the podcast date as part of the name, "This American Life • 9/29/19". So every episode now belongs to a distinct artist.

As a work-around, I wondered if I could use the new Correction Rules function with a wildcard to clean up podcast/artist names. I tried a rule: Artist Title = This American Life*, New Artist Title = This American Life. But it didn't seem to work. Does it support wildcards?

Thanks again!   =Karl=

**Comment by Rogee34** [comment]
I have encountered the same issue with Podcast Addict.

Podcast Addict actually has a setting that will turn on/off track name broadcasting specifically for scrobbling apps.

However, the new version of Simple Scrobbler seems to ignore that setting altogether, which leads me to believe that it is scraping the track info differently than before.  Hence the date glitch.

**Comment by a93h** [comment]
Thanks very much for the compliment.
I understand this issue very well.
It's somewhat on the back-burner due to bugs being higher priority.
If you know any hackers/coders who want to take a stab at it sooner than I can get to it, then by all means they can.
Closing as duplicate #489
