### ISSUE TITLE
Rocket Player is not recognized as a supported app

### ISSUE THREAD

**Issue by gprotein** [simple-last-fm-scrobbler/sls#554]
Since I updated SLS recently, it seems that the app no longer detects Rocket Player as an app. My scrobbles stopped being recorded around the start of last month. I tried uninstalling and re-installing SLS, and afterwards, it no longer detects Rocket Player at all. In Rocket Player, I have the scrobbler set to "Simple Last.fm" which worked until last month. My other music apps (Spotify and Soundcloud) continue to scrobble perfectly.

**SLS Version:** (v1.7.0)
**Issue:** Rocket Player is not recognized as a music player, does not scrobble music.
**Parameters:**
**What:** Rocket Player does not appear in Enabled Apps list, does not scrobble music from 
Rocket Player.
**Where:** Enabled Apps list
**When:** When I try to play music through Rocket Player
**Why:** I don't know
**How:** Automatic
**Android Version:** 8
**Music App(s):** Rocket Player
**Detected Music Apps(s):** Notification Default (checked), Spotify (unchecked), YouTube (unchecked)
**Enabled Settings:** 
Notification Priority: unselected
Languages: unselected
Permissions: Notification Listener (activated), Battery Optimizations (activated), External Storage (activated)
Scrobble point: 50%
On battery: Standard
Plugged in: Same as for battery
Correction Rules: none
**Phone Model:** Samsung S7

**Comment by a93h** [comment]
hmm I will need to try the newest version of Rocket Player to see if I can get it to detect SLS.
Please give me some time.

**Comment by a93h** [comment]
![Sidesync_capture_20191110192502_1](https://user-images.githubusercontent.com/8563086/68553505-fd4d7380-03ef-11ea-8616-779e50b02da0.jpg)
![Sidesync_capture_20191110192454_1](https://user-images.githubusercontent.com/8563086/68553506-fd4d7380-03ef-11ea-83a7-ad6641e2871a.jpg)

**Comment by a93h** [comment]
@gprotein I was successful at installing and running Rocket Player.
It was easily detected by Simple Scrobbler.

**Comment by a93h** [comment]
Please try this signed apk of my latest fixes, thanks.
Please use the newer apk below this one.
[deprecated](https://github.com/simple-last-fm-scrobbler/sls/files/3902826/app-debug.zip)

**Comment by a93h** [comment]
Closing as resolved for now.
