### ISSUE TITLE
Unique Sonos name is prepended to Artist name during scrobble

### ISSUE THREAD

**Issue by j7an** [simple-last-fm-scrobbler/sls#556]
SLS Version (required): (1.7.0)
Issue (required): Using SLS with Sonos Android app causes the name of the Sonos speaker to be prepended to the artist name during scrobble.
Parameters (required):
What: Incorrect artist name when scrobbling via Sonos app to Sonos speaker
Where: scrobble data
When: automated scrobble
Why: Each Sonos speaker is uniquely identified by name e.g. Office. The Sonos app controls which speaker is playing the audio.
How: Automatic
Android Version (preferred): (9)
Music App(s) (preferred): Sonos
Detected Music Apps(s) (preferred): Sonos, Apple Music, Spotify
Enabled Settings (preferred): Battery saver, Sonos, Apple Music, and Spotify
Phone Model (optional): Moto X4

It appears the correction rule feature is meant to always correct a specific artist, track, album combination. Is it even possible to use the feature to only correct the artist name when scrobbling a specific app like Sonos? For example, because my Sonos speaker is called "OFFICE", all the artists gets scrobbled as "OFFICE - <Artist Name>" format. So I'd like the rule to only remove "OFFICE -" leaving all other fields intact.

**Comment by a93h** [comment]
Thanks very much for the concise report.
I will relate you to #489 
Closing as already being discussed.
