### ISSUE TITLE
support regex patters in correction rules

### ISSUE THREAD

**Issue by casperdcl** [simple-last-fm-scrobbler/sls#560]
allow rules such as title: `^[0-9]+[\s.-]+(.*)\.mp3$` -> `\1` which would rename `01. Some track.mp3` -> `Some track`

**Comment by a93h** [comment]
Closing as already being discussed in #489

**Comment by casperdcl** [comment]
I think this is completely different from #489. #489 is about automatically doing magic. This issue (#560) is a feature request for supporting regex in user-specified rules. Fixing this issue (#560) might also help with fixing #489.

**Comment by casperdcl** [comment]
Also this issue (#560) would fix #557 since unknown fields could be filled in as `(.*)` -> `\1`.

**Comment by Efreak** [comment]
I'd appreciate this too, BubbleUPnP is adding playlist position to the track title; every track has (###/####) appended. Other tracks have information in the title that i want displayed on my phone but isn't actually part of the title (source, alternate versions, concert name, remaster, etc)
